# Setup
title:               Art in Science
tagline:             'Blog'
description:         'Loading ...'
baseurl:             '/art-in-science'
url:                 https://gayatrichandran.github.io/
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Gayatri Chandran
  url:               https://twitter.com/mdo
  email:             gayatripushpita at gmail dot com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
